/*
Sonatype Lifecycle Public REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.181.0-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeiq

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RestLegacyViolationsOrganizationOrganizationIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestLegacyViolationsOrganizationOrganizationIdPutRequest{}

// RestLegacyViolationsOrganizationOrganizationIdPutRequest struct for RestLegacyViolationsOrganizationOrganizationIdPutRequest
type RestLegacyViolationsOrganizationOrganizationIdPutRequest struct {
	AllowOverride bool `json:"allowOverride"`
	Enabled bool `json:"enabled"`
}

type _RestLegacyViolationsOrganizationOrganizationIdPutRequest RestLegacyViolationsOrganizationOrganizationIdPutRequest

// NewRestLegacyViolationsOrganizationOrganizationIdPutRequest instantiates a new RestLegacyViolationsOrganizationOrganizationIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestLegacyViolationsOrganizationOrganizationIdPutRequest(allowOverride bool, enabled bool) *RestLegacyViolationsOrganizationOrganizationIdPutRequest {
	this := RestLegacyViolationsOrganizationOrganizationIdPutRequest{}
	this.AllowOverride = allowOverride
	this.Enabled = enabled
	return &this
}

// NewRestLegacyViolationsOrganizationOrganizationIdPutRequestWithDefaults instantiates a new RestLegacyViolationsOrganizationOrganizationIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestLegacyViolationsOrganizationOrganizationIdPutRequestWithDefaults() *RestLegacyViolationsOrganizationOrganizationIdPutRequest {
	this := RestLegacyViolationsOrganizationOrganizationIdPutRequest{}
	return &this
}

// GetAllowOverride returns the AllowOverride field value
func (o *RestLegacyViolationsOrganizationOrganizationIdPutRequest) GetAllowOverride() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AllowOverride
}

// GetAllowOverrideOk returns a tuple with the AllowOverride field value
// and a boolean to check if the value has been set.
func (o *RestLegacyViolationsOrganizationOrganizationIdPutRequest) GetAllowOverrideOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AllowOverride, true
}

// SetAllowOverride sets field value
func (o *RestLegacyViolationsOrganizationOrganizationIdPutRequest) SetAllowOverride(v bool) {
	o.AllowOverride = v
}

// GetEnabled returns the Enabled field value
func (o *RestLegacyViolationsOrganizationOrganizationIdPutRequest) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *RestLegacyViolationsOrganizationOrganizationIdPutRequest) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *RestLegacyViolationsOrganizationOrganizationIdPutRequest) SetEnabled(v bool) {
	o.Enabled = v
}

func (o RestLegacyViolationsOrganizationOrganizationIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestLegacyViolationsOrganizationOrganizationIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["allowOverride"] = o.AllowOverride
	toSerialize["enabled"] = o.Enabled
	return toSerialize, nil
}

func (o *RestLegacyViolationsOrganizationOrganizationIdPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"allowOverride",
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRestLegacyViolationsOrganizationOrganizationIdPutRequest := _RestLegacyViolationsOrganizationOrganizationIdPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRestLegacyViolationsOrganizationOrganizationIdPutRequest)

	if err != nil {
		return err
	}

	*o = RestLegacyViolationsOrganizationOrganizationIdPutRequest(varRestLegacyViolationsOrganizationOrganizationIdPutRequest)

	return err
}

type NullableRestLegacyViolationsOrganizationOrganizationIdPutRequest struct {
	value *RestLegacyViolationsOrganizationOrganizationIdPutRequest
	isSet bool
}

func (v NullableRestLegacyViolationsOrganizationOrganizationIdPutRequest) Get() *RestLegacyViolationsOrganizationOrganizationIdPutRequest {
	return v.value
}

func (v *NullableRestLegacyViolationsOrganizationOrganizationIdPutRequest) Set(val *RestLegacyViolationsOrganizationOrganizationIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRestLegacyViolationsOrganizationOrganizationIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRestLegacyViolationsOrganizationOrganizationIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestLegacyViolationsOrganizationOrganizationIdPutRequest(val *RestLegacyViolationsOrganizationOrganizationIdPutRequest) *NullableRestLegacyViolationsOrganizationOrganizationIdPutRequest {
	return &NullableRestLegacyViolationsOrganizationOrganizationIdPutRequest{value: val, isSet: true}
}

func (v NullableRestLegacyViolationsOrganizationOrganizationIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestLegacyViolationsOrganizationOrganizationIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


